<?php include 'view/inc/header.inc.php'; ?>
<!--Home page for better navigation to use our system-->
<div class="container">
    <br>
    <h1 style="text-align: center;">Main Menu</h1>
    <br>
    <ul style="margin-left: 41%">
        <li>
            <a href="?page=viewclient">Clients</a>
        </li>
        <li class="nav-item">
            <a href="?page=viewemployee">Employees</a>
        </li>
        <li>
            <a href="?page=viewnotification">Notifications</a>
        </li>
        <li>
            <a href="?page=viewcnotification">Client's Notifications</a>
        </li>
        <li>
            <a href="?page=log">Log Info</a>
        </li>
    </ul>
</div>
<br>

<?php include 'view/inc/footer.inc.php'; ?>
