<?php include 'view/inc/header.inc.php'; 
include 'model/database.pdo.php';

// Fetches all data from the client table in DB
$sql_getData = $db_conn->prepare("SELECT * FROM client");
$sql_getData->execute();
$result = $sql_getData->fetchAll(PDO::FETCH_ASSOC);
?>

<!--Main page for viewing clients-->
<div class="container">
    <div class="box">
        <h5 class ="display-4 text-center">View Clients</h5>
            <table class ="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Client Id</th>
                        <th scope="col">Company Name</th>
                        <th scope="col">Business Number</th>
                        <th scope="col">Contact First Name</th>
                        <th scope="col">Contact Last Name</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Cell Number</th>
                        <th scope="col">Carrier</th>
                        <th scope="col">HST Number</th>
                        <th scope="col">Website</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!--Goes through the client table and displays data for each client-->
                    <?php foreach ($result as $client) : ?>
                    <tr>
                        <td><?php print_r($client['clientId'])?></td>
                        <td><?php print_r($client['CompanyName'])?></td>
                        <td><?php print_r($client['BusinessNumber'])?></td>
                        <td><?php print_r($client['contactFirstName'])?></td>
                        <td><?php print_r($client['contactLastName'])?></td>
                        <td><?php print_r($client['phoneNumber'])?></td>
                        <td><?php print_r($client['cellNumber'])?></td>
                        <td><?php print_r($client['carrier'])?></td>
                        <td><?php print_r($client['HST'])?></td>
                        <td><?php print_r($client['website'])?></td>
                        <td><?php print_r($client['status1'])?></td>
                        <td>
                            <!--Whichever client user decides to update, this will grab the information of that client selected-->
                            <a href="?page=editclient&cid=<?= $client['clientId'] ?>&compName=<?= $client['CompanyName'] ?>&busNum=<?= $client['BusinessNumber'] ?>&fname=<?= $client['contactFirstName'] ?>&lname=<?= $client['contactLastName'] ?>&phNum=<?= $client['phoneNumber'] ?>&cellNum=<?= $client['cellNumber']?>&carrier=<?= $client['carrier'] ?>&hst=<?= $client['HST'] ?>&website=<?= $client['website'] ?>&type=<?= $client['status1'] ?>">Edit</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <a class="btn btn-primary" href="?page=createclient" role="button">Add Client</a>
        <a class="btn btn-primary" href="?page=searchclient" role="button">Search Client</a>
        <a class="btn btn-primary" href="?page=homepage" role="button">Main Menu</a>
    </div>
</div>

<?php include 'view/inc/footer.inc.php'; ?>
<?php show_source(__file__)?>