<?php include 'view/inc/header.inc.php'; 
include 'model/database.pdo.php';

// Fetches all data in the employee table in DB
$sql_getData = $db_conn->prepare("SELECT * FROM employee");
$sql_getData->execute();
$result = $sql_getData->fetchAll(PDO::FETCH_ASSOC);
?>

<!--Main page for viewing employees-->
<div class="container">
    <div class="box">
        <h5 class ="display-4 text-center">View Employees</h5>
            <table class ="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Employee Id</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Cell Number</th>
                        <th scope="col">Position</th>
                        <th scope="col">Password</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!--Goes through the employee table and displays data for each employee-->
                    <?php foreach ($result as $employee) : ?>
                    <tr>
                        <td><?php print_r($employee['employeeId'])?></td>
                        <td><?php print_r($employee['firstName'])?></td>
                        <td><?php print_r($employee['lastName'])?></td>
                        <td><?php print_r($employee['email'])?></td>
                        <td><?php print_r($employee['cellNumber'])?></td>
                        <td><?php print_r($employee['position'])?></td>
                        <td><?php print_r($employee['e_password'])?></td>
                        <td><?php print_r($employee['status1'])?></td>
                        <td>
                            <!--Whichever employee user decides to update, this will grab the information of that employee selected-->
                            <a href="?page=editemployee&eid=<?= $employee['employeeId'] ?>&efname=<?= $employee['firstName'] ?>&elname=<?= $employee['lastName'] ?>&eemail=<?= $employee['email'] ?>&ecell=<?= $employee['cellNumber'] ?>&position=<?= $employee['position'] ?>&password=<?= $employee['e_password']?>&type=<?= $employee['status1'] ?>">Edit</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <a class="btn btn-primary" href="?page=createemployee" role="button">Add Employee</a>
        <a class="btn btn-primary" href="?page=searchemployee" role="button">Search Employee</a>
        <a class="btn btn-primary" href="?page=homepage" role="button">Main Menu</a>
    </div>
</div>

<?php include 'view/inc/footer.inc.php'; ?>
<?php show_source(__file__)?>